name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Build 🔧
        run: mkdir dist && python3 build_plugin.py --out-dir dist dw235 "plugins/*.js"

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: dist # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
